export interface PremiumTitleModel {
    id: string;
    name: string;
    group: 'Impacto Social' | 'Vendas & Conversão' | 'Editorial & Marca';
    description: string;
    sample: string;
    primaryColor: string;
    secondaryColor: string;
    fontFamily: string;
}

export const PREMIUM_TITLE_MODELS: PremiumTitleModel[] = [
    {
        id: 'premium-kinetic-punch',
        name: 'Kinetic Punch',
        group: 'Impacto Social',
        description: 'Palavra-chave gigante com entrada elástica e sombra gráfica.',
        sample: 'PARE TUDO',
        primaryColor: '#C7FF3D',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Archivo Black',
    },
    {
        id: 'premium-sticker-pop',
        name: 'Sticker Pop',
        group: 'Impacto Social',
        description: 'Adesivo vibrante para dicas, reações e chamadas rápidas.',
        sample: 'OLHA ISSO!',
        primaryColor: '#FF4FD8',
        secondaryColor: '#FFF8E7',
        fontFamily: 'Archivo Black',
    },
    {
        id: 'premium-marker-swipe',
        name: 'Marker Swipe',
        group: 'Impacto Social',
        description: 'Marca-texto animado que conduz a leitura sem poluir.',
        sample: 'SEGREDO REVELADO',
        primaryColor: '#FFE600',
        secondaryColor: '#111318',
        fontFamily: 'League Spartan',
    },
    {
        id: 'premium-split-block',
        name: 'Split Block',
        group: 'Impacto Social',
        description: 'Duas faixas em sequência para frases curtas de alto impacto.',
        sample: 'VOCÊ PRECISA VER',
        primaryColor: '#00E6A8',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Anton',
    },
    {
        id: 'premium-outline-echo',
        name: 'Outline Echo',
        group: 'Impacto Social',
        description: 'Eco tipográfico com profundidade e energia de videoclipe.',
        sample: 'NOVIDADE',
        primaryColor: '#7C5CFF',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Archivo Black',
    },
    {
        id: 'premium-creator-caption',
        name: 'Creator Caption',
        group: 'Impacto Social',
        description: 'Cartela editorial compacta para opiniões e frases de criador.',
        sample: 'MINHA OPINIÃO SINCERA',
        primaryColor: '#14E6FF',
        secondaryColor: '#FFFFFF',
        fontFamily: 'DM Sans',
    },
    {
        id: 'premium-sale-spotlight',
        name: 'Sale Spotlight',
        group: 'Vendas & Conversão',
        description: 'Oferta principal com selo, brilho controlado e leitura imediata.',
        sample: 'OFERTA IMPERDÍVEL',
        primaryColor: '#FF2D55',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Archivo Black',
    },
    {
        id: 'premium-price-tag',
        name: 'Price Tag Pro',
        group: 'Vendas & Conversão',
        description: 'Etiqueta comercial premium para preço, desconto ou condição.',
        sample: 'SÓ R$ 39,90',
        primaryColor: '#FFB800',
        secondaryColor: '#111318',
        fontFamily: 'League Spartan',
    },
    {
        id: 'premium-urgency-pulse',
        name: 'Urgency Pulse',
        group: 'Vendas & Conversão',
        description: 'Alerta sofisticado para prazo, lote e escassez.',
        sample: 'ÚLTIMAS UNIDADES',
        primaryColor: '#FF3B30',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Anton',
    },
    {
        id: 'premium-coupon-ticket',
        name: 'Coupon Ticket',
        group: 'Vendas & Conversão',
        description: 'Cupom destacável com recorte visual e código evidente.',
        sample: 'CUPOM MILETO20',
        primaryColor: '#7CFF6B',
        secondaryColor: '#101510',
        fontFamily: 'Space Grotesk',
    },
    {
        id: 'premium-benefit-badge',
        name: 'Benefit Badge',
        group: 'Vendas & Conversão',
        description: 'Benefício validado em cartela limpa para gerar confiança.',
        sample: 'ENTREGA GRÁTIS',
        primaryColor: '#00D084',
        secondaryColor: '#FFFFFF',
        fontFamily: 'DM Sans',
    },
    {
        id: 'premium-product-launch',
        name: 'Product Launch',
        group: 'Vendas & Conversão',
        description: 'Lançamento de produto com acabamento tecnológico e premium.',
        sample: 'CONHEÇA O NOVO',
        primaryColor: '#8B5CFF',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Space Grotesk',
    },
    {
        id: 'premium-luxury-editorial',
        name: 'Luxury Editorial',
        group: 'Editorial & Marca',
        description: 'Serifa elegante, filetes dourados e ritmo de campanha de luxo.',
        sample: 'ESSÊNCIA ÚNICA',
        primaryColor: '#D8B56D',
        secondaryColor: '#FFF9EE',
        fontFamily: 'Playfair Display',
    },
    {
        id: 'premium-swiss-modern',
        name: 'Swiss Modern',
        group: 'Editorial & Marca',
        description: 'Grid suíço, índice e alinhamento preciso para marcas modernas.',
        sample: 'DESIGN QUE FUNCIONA',
        primaryColor: '#FF4D36',
        secondaryColor: '#FFFFFF',
        fontFamily: 'DM Sans',
    },
    {
        id: 'premium-glass-prism',
        name: 'Glass Prism',
        group: 'Editorial & Marca',
        description: 'Vidro escuro com reflexo prismático e profundidade discreta.',
        sample: 'VISÃO DE FUTURO',
        primaryColor: '#5DEBFF',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Space Grotesk',
    },
    {
        id: 'premium-cinema-chapter',
        name: 'Cinema Chapter',
        group: 'Editorial & Marca',
        description: 'Capítulo cinematográfico para storytelling, cases e manifestos.',
        sample: 'UMA NOVA HISTÓRIA',
        primaryColor: '#E7C27D',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Montserrat',
    },
    {
        id: 'premium-magazine-stack',
        name: 'Magazine Stack',
        group: 'Editorial & Marca',
        description: 'Composição de capa com texto empilhado e contraste editorial.',
        sample: 'BELEZA EM MOVIMENTO',
        primaryColor: '#FF5A6F',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Bebas Neue',
    },
    {
        id: 'premium-chrome-future',
        name: 'Chrome Future',
        group: 'Editorial & Marca',
        description: 'Metal cromado contemporâneo para tecnologia, moda e automóveis.',
        sample: 'PRÓXIMO NÍVEL',
        primaryColor: '#64E9FF',
        secondaryColor: '#FFFFFF',
        fontFamily: 'Archivo Black',
    },
];

export const PREMIUM_TITLE_GROUPS: PremiumTitleModel['group'][] = [
    'Impacto Social',
    'Vendas & Conversão',
    'Editorial & Marca',
];
